//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
//<auto-generated>
//  This code was generated by a tool
//  Runtime Version: 4.0.30319.42000
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//</auto-generated>
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
using System;
using System.CodeDom.Compiler;

namespace Store.Tests.Unit.Framework.Builders
{

    [GeneratedCode("Builders", "1.0")]
    public partial class AddressBuilder : Builder<Store.Domain.Models.Address>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class CategoryBuilder : Builder<Store.Domain.Models.Category>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class CountryBuilder : Builder<Store.Domain.Models.Country>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class EFMigrationsHistoryBuilder : Builder<Store.Domain.Models.EFMigrationsHistory>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class OrderBuilder : Builder<Store.Domain.Models.Order>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class OrderItemBuilder : Builder<Store.Domain.Models.OrderItem>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class OrderStatusBuilder : Builder<Store.Domain.Models.OrderStatus>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class ProductBuilder : Builder<Store.Domain.Models.Product>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class ProductStatusBuilder : Builder<Store.Domain.Models.ProductStatus>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class StateBuilder : Builder<Store.Domain.Models.State>
    {
    }

    [GeneratedCode("Builders", "1.0")]
    public partial class UserBuilder : Builder<Store.Domain.Models.User>
    {
    }

}
